services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "pnr_db"
      POSTGRES_DB: "pnr_db"
    restart: always
    networks:
      - db_network

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin_service
#    ports:
#      - "8083:80"  # Map pgAdmin to port 8080 on your host machine
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"  # Change this to your desired login email
#      PGADMIN_DEFAULT_PASSWORD: "admin"          # Change this to your desired login password
#    restart: always
#    depends_on:
#      - postgres-db
#    networks:
#      - db_network

  kafka:
    image: apache/kafka:latest
    container_name: kafka_service
    ports:
      - "9092:9092"
    environment:
      # Use a unique cluster ID (Required for KRaft)
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Generate a random UUID for the cluster ID
      - KAFKA_CLUSTER_ID=praveen_kafka_cluster_2026
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1

networks:
  db_network:
    driver: bridge