version: '3.9'

services:

  postgres-service:
    image: postgres:16-alpine
    container_name: postgres-service
    command: ["postgres", "-c", "max_connections=300"]
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: pnr_db
      POSTGRES_PASSWORD: pnr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  kafka-service:
    image: apache/kafka:latest
    container_name: kafka-service
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # 🌟 Keep these exactly as they are so Kafka binds port 29092 internally
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka-service:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-service:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_CLUSTER_ID: praveen_kafka_cluster_2026

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    restart: unless-stopped

  schema-registry:
    image: confluentinc/cp-schema-registry:8.1.0
    container_name: schema-registry
    ports:
      - "9081:9081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:9081'

      # 🌟 CRITICAL FIX: Changed from 'INTERNAL://...' to 'PLAINTEXT://...'
      # This tells Schema Registry to use standard PLAINTEXT formatting over port 29092.
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka-service:29092'

    depends_on:
      - kafka-service
    restart: unless-stopped

volumes:
  postgres_data: