spring:
  application:
    name: simulator
  threads:
    virtual:
      enabled: true # Enable Java 21 Virtual Threads natively
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${db-host:localhost}:${DB_PORT:5432}/${postgres-db:pnr_db}
    driver-class-name: org.postgresql.Driver
    username: ${postgres-user:root}
    password: ${postgres-password:pnr_db}
# Cap individual pods so they don't hoard connections
    hikari:
      maximum-pool-size=4:
  kafka:
    bootstrap-servers: kafka-service:29092

    consumer:
      isolation-level: read_committed
      enable-auto-commit: false
#      auto-offset-reset: earliest
#      group-id: skyflying-eos-group # Make sure this is present
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring.deserializer.key.delegate: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: http://localhost:9081
        specific.avro.reader: true
    producer:
      acks: all
      transaction-id: tx-dcs-booking-
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:9081
    template:
      observation-enabled: true
    listener:
      ack-mode: MANUAL_IMMEDIATE
      observation-enabled: true
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  Zipkin:
    tracing:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: "health,liveness,readiness,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: api-pnr-gateway
server:
  port: ${SERVER_PORT:8080}
logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}]"
