package com.praveen.simulator.service;

import com.praveen.simulator.dto.PassengerRequest;
import com.praveen.simulator.entity.Passenger;
import com.praveen.simulator.helper.AirlineException;
import com.praveen.simulator.helper.CommonMapper;
import com.praveen.simulator.repository.PassengerRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
@Slf4j
public class PassengerService {

    private final PassengerRepository passengerRepository;
    private final CommonMapper commonMapper;

    /**
     * Registers a unique passenger into the core airline platform.
     * Fixed: Wrapped in a write-transaction context.
     * Fixed: Shifted duplication lookup from artificial sequence ID to business unique natural criteria.
     */
    @Transactional
    public Passenger addPassenger(PassengerRequest passengerRequest) {
        log.info("Checking passenger unique registry criteria for Identity: {}", passengerRequest);

        // Production Standard: Check by natural unique attributes, not autogenerated sequence IDs
        if (passengerRequest.getDocumentDetails()!=null && passengerRequest.getDocumentDetails().getPassportNumber()!=null && passengerRepository.existsByDocumentDetails_PassportNumber(passengerRequest.getDocumentDetails().getPassportNumber())) {
            throw AirlineException.conflict("Cannot register passenger. A profile already exists matching passport reference: "
                    + passengerRequest.getDocumentDetails().getPassportNumber());
        }

        if (passengerRepository.existsByEmail(passengerRequest.getEmail())) {
            throw AirlineException.conflict("Passenger with this email id exists matching reference: "
                    + passengerRequest.getEmail());
        }

        log.info("Mapping payload to domain entity for new passenger registration.");
        Passenger passenger = commonMapper.toPassenger(passengerRequest);

        Passenger savedPassenger = passengerRepository.save(passenger);
        log.info("Passenger successfully committed to database with system profile ID: {}", savedPassenger.getId());
        return savedPassenger;
    }

    /**
     * Performs a stateful mutation updates on a managed passenger entity record.
     * Fixed: Annotated with @Transactional.
     */
    @Transactional
    public Passenger update(Passenger passenger) {
        log.info("Updating passenger profile state for System ID: {}", passenger.getId());
        Passenger savedPassenger = passengerRepository.save(passenger);
        log.debug("Passenger changes successfully synchronized to system db registry.");
        return savedPassenger;
    }

    /**
     * Retrieve a passenger profile from the persistent tier using their unique primary system identifier.
     * Fixed: Enforced connection-level readOnly hint optimization.
     */
    @Transactional(readOnly = true)
    public Optional<Passenger> getPassengerById(int id) {
        return passengerRepository.findById(id);
    }

    /**
     * Fetches all registered passengers globally from the platform system.
     * Fixed: Optimized with readOnly transactional context.
     */
    @Transactional(readOnly = true)
    public List<Passenger> getAllPassengers() {
        log.debug("Fetching baseline complete passenger listing from database records...");
        return passengerRepository.findAll();
    }
}